---
- name: '[dependencies] Make sure curl package is installed'
  apt:
    name: curl
    state: present
    update_cache: yes  # This is a must for the installer to not fail at first run
  become: yes
  tags:
    - pihole
    - pihole_dependencies
...
