---
- name: '[dependencies] Update apt in order the installer to not fail at first run'
  apt:
    update_cache: yes
  become: yes
  tags:
    - pihole
    - pihole_dependencies

- name: '[dependencies] Make sure curl and git packages are installed'
  apt:
    name:
      - curl
      - git
    state: present
  become: yes
  tags:
    - pihole
    - pihole_dependencies
...
