---
# tasks file for ansible-pihole

# PIHOLE
- name: '[main] Include dependencies tasks'
  include_tasks: dependencies.yml
  tags:
    - pihole
    - pihole_dependencies

- name: '[main] Check if pihole is already installed'
  stat: path=/usr/local/bin/pihole
  register: pihole
  tags:
    - pihole

- name: '[main] Make sure /etc/pihole directory exists'
  file:
    state: directory
    path: /etc/pihole
    owner: root
    group: root
    mode: 0755
  become: yes
  tags:
    - pihole

- name: '[main] Generate /etc/pihole/setupVars.conf for unattended pihole install'
  template:
    src: setupVars.conf.j2
    dest: /etc/pihole/setupVars.conf
    owner: root
    group: root
    mode: 0644
  become: yes
  when: not pihole.stat.exists or ( pihole.stat.exists and pihole_force_upgrade )
  tags:
    - pihole

- name: '[main] Download pihole installer script'
  get_url:
    url: https://install.pi-hole.net
    dest: /tmp/pihole.sh
  tags:
    - pihole

- name: '[main] Install pihole'
  shell: 'bash /tmp/pihole.sh --unattended'
  ignore_errors: yes
  become: yes
  when: not pihole.stat.exists or ( pihole.stat.exists and pihole_force_upgrade )
  tags:
    - pihole

- name: '[main] Generate /etc/dnsmasq.d/03-custom.conf'
  template:
    src: 03-custom.conf.j2
    dest: /etc/dnsmasq.d/03-custom.conf
  become: yes
  notify: Restart dnsmasq
  tags:
    - pihole

- name: '[main] make sure dns is set to 127.0.0.1'
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
  become: yes
  tags:
    - pihole

- name: '[main] Check if "i" file attribute for /etc/resolv.conf is set'
  shell: lsattr /etc/resolv.conf | cut -d ' ' -f 1 | grep -q "i"
  register: pihole_resolv_conf_attrib_i
  changed_when: false
  failed_when: false
  tags:
    - pihole

# Attention! If /etc/resolv.conf needs to be unlocked and changed, run in root shell:
# chattr -i /etc/resolv.conf
- name: '[main] Lock /etc/resolv.conf making sure it will always stay the same'
  command: chattr +i /etc/resolv.conf
  become: yes
  when: pihole_resolv_conf_attrib_i.rc != 0
  tags:
    - pihole

- name: '[main] Include DNSCrypt related tasks'
  include_tasks: DNSCrypt.yml
  when: pihole_dnscrypt
  tags:
    - pihole
    - dnscrypt
    - dnscrypt_systemd

- meta: flush_handlers
  tags:
    - pihole
    - dnscrypt
    - dnscrypt_systemd
...
