---
# tasks file for ansible-pihole

# PIHOLE
- name: '[main] Include dependencies tasks'
  include_tasks: dependencies.yml
  tags:
    - pihole
    - pihole_dependencies

- name: '[main] Check if pihole is already installed'
  stat: path=/usr/local/bin/pihole
  register: pihole
  tags:
    - pihole

- name: '[main] Make sure /etc/pihole directory exists'
  file:
    state: directory
    path: /etc/pihole
    owner: root
    group: root
    mode: 0755
  become: yes
  tags:
    - pihole

- name: '[main] Clone pihole repo'
  git:
    repo: https://github.com/pi-hole/pi-hole.git
    depth: 1
    dest: /tmp/pi-hole
    version: master
  tags:
    - pihole

- name: '[main] Check if /etc/pihole/setupVars.conf already exists'
  stat: path=/etc/pihole/setupVars.conf
  register: pihole_setupVars
  tags:
   - pihole

- name: '[main] Generate /etc/pihole/setupVars.conf for unattended pihole install if it does not exist or if upgrading'
  template:
    src: setupVars.conf.j2
    dest: /etc/pihole/setupVars.conf
    owner: root
    group: root
    mode: 0644
  register: pihole_setupVars_generated
  become: yes
  when: not pihole_setupVars.stat.exists or pihole_force_upgrade
  tags:
    - pihole

- name: '[main] Install pihole'
  command: 'bash /tmp/pi-hole/automated\ install/basic-install.sh --unattended'
  become: yes
  when:
    - pihole_setupVars_generated.changed or pihole_setupVars.stat.exists
    - not pihole.stat.exists or pihole_force_upgrade
  tags:
    - pihole

- name: '[main] Set cron job for daily pihole updates'
  cron:
    name: "daily pihole updater"
    user: "www-data"
    minute: "0"
    hour: "4"
    job: "/usr/local/bin/pihole -up"
  become: yes
  tags:
    - pihole

- name: '[main] Include drew-kun.resolv role'
  include_role:
    name: drew-kun.resolv
  vars:
    resolv_nameservers: [127.0.0.1]
    resolv_lock: yes
  when: pihole_resolv
  tags:
    - pihole
...
