---
# tasks file for ansible-pihole

# PIHOLE
- name: '[main] Include dependencies tasks'
  include_tasks: dependencies.yml
  tags:
    - pihole
    - pihole_dependencies

- name: '[main] Check if pihole is already installed'
  stat: path=/usr/local/bin/pihole
  register: pihole
  tags:
    - pihole

- name: '[main] Make sure /etc/pihole directory exists'
  file:
    state: directory
    path: /etc/pihole
    owner: root
    group: root
    mode: 0755
  become: yes
  tags:
    - pihole

- name: '[main] Generate /etc/pihole/setupVars.conf for unattended pihole install'
  template:
    src: setupVars.conf.j2
    dest: /etc/pihole/setupVars.conf
    owner: root
    group: root
    mode: 0644
  become: yes
  when: not pihole.stat.exists or pihole_force_upgrade
  tags:
    - pihole

- name: '[main] Check if /tmp/pihole.sh exists'
  stat: path=/tmp/pihole.sh
  register: pihole_downloaded
  tags:
    - pihole

- name: '[main] Download pihole installer script'
  get_url:
    url: https://install.pi-hole.net
    dest: /tmp/pihole.sh
  when: not pihole_downloaded.stat.exists or pihole_force_upgrade
  tags:
    - pihole

- name: '[main] Install pihole'
  shell: 'bash /tmp/pihole.sh --unattended'
  become: yes
  when: not pihole.stat.exists or ( pihole.stat.exists and pihole_force_upgrade )
  tags:
    - pihole

#==== Temporary (hopefully) fix of 'pihole.sh --unattended' bug: ========
- name: '[main] Create user pihole because installer fails to create the one'
  user:
    name: pihole
    shell: /usr/sbin/nologin
    password: "{{ pihole_user_passwd }}"
    append: yes
  become: yes

- name: '[main] Restart pihole-FTL service'
  service: name=pihole-FTL state=restarted
  become: yes

- name: '[main] Run `lighty-enable-mod fastcgi fastcgi-php`'
  command: lighty-enable-mod fastcgi fastcgi-php
  become: yes
  register: pihole_lighty
  changed_when: pihole_lighty.rc == 0
  failed_when: pihole_lighty.rc != 0 and pihole_lighty.rc !=2 # $? = 2 - already enabled

- name: '[main] Force-reload lighttpd service'
  command: service lighttpd force-reload
  become: yes
#========================================================================

- name: '[main] Generate /etc/dnsmasq.d/03-custom.conf'
  template:
    src: 03-custom.conf.j2
    dest: /etc/dnsmasq.d/03-custom.conf
  become: yes
  notify: Restart dnsmasq
  tags:
    - pihole

# The pitft role is not finished because the script does not provide non-interactive way of running
#- name: '[main] Include drew-kun.pitft role'
#  include_role:
#    name: drew-kun.pitft
#  when: pihole_pitft
#  tags:
#    - pihole
#    - pihole_pitft

- name: '[main] Include DNSCrypt related tasks'
  include_tasks: DNSCrypt.yml
  when: pihole_dnscrypt
  tags:
    - pihole
    - pihole_dnscrypt

- name:
  include_role:
    name: drew-kun.resolv
  vars:
    resolv_nameservers: [127.0.0.1]
    resolv_lock: yes
  tags:
    - pihole

- meta: flush_handlers
  tags:
    - pihole
    - pihole_dnscrypt
#    - pihole_pitft
...
