---
# tasks file for ansible-pihole

# PIHOLE
- name: '[main] Include dependencies tasks'
  include_tasks: dependencies.yml
  tags:
    - pihole
    - pihole_dependencies

- name: '[main] Check if pihole is already installed'
  stat: path=/usr/local/bin/pihole
  register: pihole
  tags:
    - pihole

- name: '[main] Make sure /etc/pihole directory exists'
  file:
    state: directory
    path: /etc/pihole
    owner: root
    group: root
    mode: 0755
  become: yes
  tags:
    - pihole

##==== Better installing algorithm (doesn't work now ) =======
## Installer is broken in master branch ( hangs on 36% of installation)
#- name: '[main] Clone pihole repo'
#  git:
#    repo: https://github.com/pi-hole/pi-hole.git
#    depth: 1
#    dest: /tmp/pi-hole
#    version: master  # master git branch
#  tags:
#    - pihole
#
#- name: '[main] Check if /etc/pihole/setupVars.conf already exists'
#  stat: path=/etc/pihole/setupVars.conf
#  register: pihole_setupVars
#  tags:
#   - pihole
#
#- name: '[main] Generate /etc/pihole/setupVars.conf for unattended pihole install if it does not exist or if upgrading'
#  template:
#    src: setupVars.conf.j2
#    dest: /etc/pihole/setupVars.conf
#    owner: root
#    group: root
#    mode: 0644
#  become: yes
#  when: not pihole_setupVars.stat.exists or pihole_force_upgrade
#  tags:
#    - pihole
#
#- name: '[main] Install pihole'
#  command: 'bash /tmp/pi-hole/automated\ install/basic-install.sh --unattended'
#  become: yes
#  when:
#    - pihole_setupVars.stat.exists
#    - not pihole.stat.exists or pihole_force_upgrade
#  tags:
#    - pihole
##=======================================================================

##=======================================================================
## Remove this section when master branch is fixed
- name: '[main] Check if /tmp/pihole.sh exists'
  stat: path=/tmp/pihole.sh
  register: pihole_downloaded
  tags:
    - pihole

- name: '[main] Check if /etc/pihole/setupVars.conf already exists'
  stat: path=/etc/pihole/setupVars.conf
  register: pihole_setupVars
  tags:
   - pihole

- name: '[main] Generate /etc/pihole/setupVars.conf for unattended pihole install if it does not exist or if upgrading'
  template:
    src: setupVars.conf.j2
    dest: /etc/pihole/setupVars.conf
    owner: root
    group: root
    mode: 0644
  become: yes
  when: not pihole_setupVars.stat.exists or pihole_force_upgrade
  tags:
    - pihole

- name: '[main] Download pihole installer script'
  get_url:
    url: https://install.pi-hole.net
    dest: /tmp/pihole.sh
  when: not pihole_downloaded.stat.exists or pihole_force_upgrade
  tags:
    - pihole

- name: '[main] Install pihole'
  shell: 'bash /tmp/pihole.sh --unattended'
  become: yes
  when:
    - pihole_setupVars.stat.exists
    - not pihole.stat.exists or pihole_force_upgrade
  tags:
    - pihole
#========================================================================

#==== Temporary (hopefully) fix of 'pihole.sh --unattended' bug: ========
- name: '[main] Include pihole installer fix tasks'
  include_tasks: installer_fix.yml
  when: pihole_dnscrypt
  tags:
    - pihole_fix
#========================================================================

- name: '[main] Generate /etc/dnsmasq.d/03-custom.conf'
  template:
    src: 03-custom.conf.j2
    dest: /etc/dnsmasq.d/03-custom.conf
  become: yes
  ### dnsmasq will be removed in favour of FTLDNS
  notify: Restart dnsmasq
  tags:
    - pihole

- name: '[main] Set cron job for daily pihole updates'
  cron:
    name: "daily pihole updater"
    user: "www-data"
    minute: "0"
    hour: "4"
    job: "/usr/local/bin/pihole -up"
  become: yes
  tags:
    - pihole

- name: '[main] Include drew-kun.dnscrypt role'
  include_role:
    name: drew-kun.dnscrypt
  vars:
    dnscrypt_on_pihole: yes
  tags:
    - pihole
    - pihole_dnscrypt

- name: '[main] Include drew-kun.resolv role'
  include_role:
    name: drew-kun.resolv
  vars:
    resolv_nameservers: [127.0.0.1]
    resolv_lock: yes
  tags:
    - pihole

- meta: flush_handlers
  tags:
    - pihole
    - pihole_dnscrypt
...
