---
# handlers file for ansible-pihole

- name: Restart dnsmasq
  service: name=dnsmasq state=restarted
  become: yes

- name: Run 'dnscrypt-proxy -service restart'
  command: /opt/dnscrypt-proxy/dnscrypt-proxy -service restart
  become: yes

- name: Restart dnscrypt-proxy.servcie systemd unit
  service: name=dnscrypt-proxy.service state=restarted
  become: yes
...
